FROM nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu18.04

RUN echo "deb [trusted=yes] http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list
RUN echo "deb [trusted=yes] http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget bzip2 && \
    rm -rf /var/lib/apt/lists/*

# Download and install Miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# Set path for Miniconda
ENV PATH="/opt/conda/bin:${PATH}"

# Create a new conda environment
COPY environment.yaml .
RUN conda env create -f environment.yaml

# Activate the conda environment
RUN echo "conda activate myenv" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

# Set the working directory to /app
WORKDIR /app

# Copy the fine_tune_gpu.py file into the container at /app
COPY fine_tune_gpu.py .

# Set environment variables for CUDA runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Set the entrypoint to run the fine_tune_gpu.py file
ENTRYPOINT ["python", "fine_tune_gpu.py"]
